# Generated by Django 4.2.1 on 2023-05-16 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajos',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baterias',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guitarra',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='microfonos',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bajos',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='baterias',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guitarra',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='microfonos',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
