# Generated by Django 4.2 on 2023-05-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_bajos_creador_baterias_creador_guitarra_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajos',
            name='creador',
        ),
    ]
